# Generated by Django 2.2.12 on 2020-05-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pcalc_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('0', 'М'), ('1', 'Ж')], default='0', max_length=10)),
                ('year_born', models.CharField(max_length=10)),
                ('year_begin', models.CharField(default='2015', max_length=10)),
                ('army', models.CharField(max_length=10)),
                ('child', models.CharField(max_length=10)),
                ('other', models.CharField(max_length=10)),
                ('ts01', models.CharField(default='0', max_length=10)),
                ('ts91', models.CharField(default='0', max_length=10)),
                ('ts14', models.CharField(default='12', max_length=10)),
                ('szar5', models.CharField(max_length=20)),
                ('szar2', models.CharField(max_length=20)),
                ('szar14', models.CharField(max_length=20)),
                ('szar15', models.CharField(max_length=20)),
                ('sv', models.CharField(max_length=10)),
                ('stn1', models.CharField(max_length=10)),
                ('stn2', models.CharField(max_length=10)),
                ('stl1', models.CharField(max_length=10)),
                ('stl2', models.CharField(max_length=10)),
                ('pensia', models.CharField(max_length=40)),
            ],
        ),
    ]
