# Generated by Django 2.2.12 on 2020-06-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcalc', '0002_auto_20200531_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcalc_info',
            old_name='sv',
            new_name='sam',
        ),
        migrations.AddField(
            model_name='pcalc_info',
            name='ssam',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='pcalc_info',
            name='sts',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
